/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;
import java.awt.Toolkit;


/**
 *
 * @author Manuel
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.setSize(240,300);
    }
    String cadena="",operacion="",cadena2="";
    double result=0,numero=0,numero2=0,resultado=0,ans=0;
    boolean op=false;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton27 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lineBorder1 = (javax.swing.border.LineBorder)javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0));
        jPanel3 = new javax.swing.JPanel();
        num7 = new javax.swing.JButton();
        entre = new javax.swing.JButton();
        por = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        mas = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        menos = new javax.swing.JButton();
        num0 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        coma = new javax.swing.JButton();
        num1 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        raiz = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        back = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        negar = new javax.swing.JButton();
        unoentre = new javax.swing.JButton();
        porcentaje = new javax.swing.JButton();
        salida2 = new javax.swing.JLabel();
        salida = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Opciones = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jButton27.setText(" ");

        jButton9.setText("=");

        jButton29.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jButton29.setText("√");
        jButton29.setAlignmentY(0.7F);
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(41, 247, 244));
        setBounds(new java.awt.Rectangle(475, 200, 0, 0));
        setResizable(false);
        getContentPane().setLayout(null);

        num7.setBackground(new java.awt.Color(225, 251, 255));
        num7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        num7.setForeground(new java.awt.Color(255, 255, 255));
        num7.setText("7");
        num7.setAlignmentY(0.7F);
        num7.setContentAreaFilled(false);
        num7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7ActionPerformed(evt);
            }
        });
        getContentPane().add(num7);
        num7.setBounds(10, 114, 41, 30);

        entre.setBackground(new java.awt.Color(225, 251, 255));
        entre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        entre.setForeground(new java.awt.Color(255, 255, 255));
        entre.setText("/");
        entre.setAlignmentY(0.7F);
        entre.setContentAreaFilled(false);
        entre.setMargin(new java.awt.Insets(0, 0, 0, 0));
        entre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entreActionPerformed(evt);
            }
        });
        getContentPane().add(entre);
        entre.setBounds(139, 114, 41, 30);

        por.setBackground(new java.awt.Color(225, 251, 255));
        por.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        por.setForeground(new java.awt.Color(255, 255, 255));
        por.setText("*");
        por.setAlignmentY(0.7F);
        por.setContentAreaFilled(false);
        por.setMargin(new java.awt.Insets(0, 0, 0, 0));
        por.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porActionPerformed(evt);
            }
        });
        getContentPane().add(por);
        por.setBounds(139, 146, 41, 30);

        num5.setBackground(new java.awt.Color(225, 251, 255));
        num5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        num5.setForeground(new java.awt.Color(255, 255, 255));
        num5.setText("5");
        num5.setAlignmentY(0.7F);
        num5.setContentAreaFilled(false);
        num5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });
        getContentPane().add(num5);
        num5.setBounds(53, 146, 41, 30);

        num6.setBackground(new java.awt.Color(225, 251, 255));
        num6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        num6.setForeground(new java.awt.Color(255, 255, 255));
        num6.setText("6");
        num6.setAlignmentY(0.7F);
        num6.setContentAreaFilled(false);
        num6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6ActionPerformed(evt);
            }
        });
        getContentPane().add(num6);
        num6.setBounds(96, 146, 41, 30);

        mas.setBackground(new java.awt.Color(225, 251, 255));
        mas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mas.setForeground(new java.awt.Color(255, 255, 255));
        mas.setText("+");
        mas.setAlignmentY(0.7F);
        mas.setContentAreaFilled(false);
        mas.setMargin(new java.awt.Insets(0, 0, 0, 0));
        mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masActionPerformed(evt);
            }
        });
        getContentPane().add(mas);
        mas.setBounds(139, 178, 41, 30);

        num4.setBackground(new java.awt.Color(225, 251, 255));
        num4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        num4.setForeground(new java.awt.Color(255, 255, 255));
        num4.setText("4");
        num4.setAlignmentY(0.7F);
        num4.setContentAreaFilled(false);
        num4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });
        getContentPane().add(num4);
        num4.setBounds(10, 146, 41, 30);

        num3.setBackground(new java.awt.Color(225, 251, 255));
        num3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        num3.setForeground(new java.awt.Color(255, 255, 255));
        num3.setText("3");
        num3.setAlignmentY(0.7F);
        num3.setContentAreaFilled(false);
        num3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });
        getContentPane().add(num3);
        num3.setBounds(96, 178, 41, 30);

        menos.setBackground(new java.awt.Color(225, 251, 255));
        menos.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        menos.setForeground(new java.awt.Color(255, 255, 255));
        menos.setText("-");
        menos.setAlignmentY(0.7F);
        menos.setContentAreaFilled(false);
        menos.setMargin(new java.awt.Insets(0, 0, 0, 0));
        menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosActionPerformed(evt);
            }
        });
        getContentPane().add(menos);
        menos.setBounds(182, 178, 41, 30);

        num0.setBackground(new java.awt.Color(225, 251, 255));
        num0.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        num0.setForeground(new java.awt.Color(255, 255, 255));
        num0.setText("0");
        num0.setContentAreaFilled(false);
        num0.setDoubleBuffered(true);
        num0.setMargin(new java.awt.Insets(0, 0, 0, 0));
        num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num0ActionPerformed(evt);
            }
        });
        getContentPane().add(num0);
        num0.setBounds(10, 210, 84, 30);

        num8.setBackground(new java.awt.Color(225, 251, 255));
        num8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        num8.setForeground(new java.awt.Color(255, 255, 255));
        num8.setText("8");
        num8.setAlignmentY(0.7F);
        num8.setContentAreaFilled(false);
        num8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });
        getContentPane().add(num8);
        num8.setBounds(53, 114, 41, 30);

        num2.setBackground(new java.awt.Color(225, 251, 255));
        num2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        num2.setForeground(new java.awt.Color(255, 255, 255));
        num2.setText("2");
        num2.setAlignmentY(0.7F);
        num2.setContentAreaFilled(false);
        num2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });
        getContentPane().add(num2);
        num2.setBounds(53, 178, 41, 30);

        coma.setBackground(new java.awt.Color(225, 251, 255));
        coma.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        coma.setForeground(new java.awt.Color(255, 255, 255));
        coma.setText(",");
        coma.setContentAreaFilled(false);
        coma.setMargin(new java.awt.Insets(0, 0, 0, 0));
        coma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comaActionPerformed(evt);
            }
        });
        getContentPane().add(coma);
        coma.setBounds(96, 210, 41, 30);

        num1.setBackground(new java.awt.Color(225, 251, 255));
        num1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        num1.setForeground(new java.awt.Color(255, 255, 255));
        num1.setText("1");
        num1.setAlignmentY(0.7F);
        num1.setContentAreaFilled(false);
        num1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });
        getContentPane().add(num1);
        num1.setBounds(10, 178, 41, 30);

        num9.setBackground(new java.awt.Color(225, 251, 255));
        num9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        num9.setForeground(new java.awt.Color(255, 255, 255));
        num9.setText("9");
        num9.setAlignmentY(0.7F);
        num9.setContentAreaFilled(false);
        num9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });
        getContentPane().add(num9);
        num9.setBounds(96, 114, 41, 30);

        raiz.setBackground(new java.awt.Color(225, 251, 255));
        raiz.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        raiz.setForeground(new java.awt.Color(255, 255, 255));
        raiz.setText("√");
        raiz.setAlignmentY(0.7F);
        raiz.setContentAreaFilled(false);
        raiz.setMargin(new java.awt.Insets(0, 0, 0, 0));
        raiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raizActionPerformed(evt);
            }
        });
        getContentPane().add(raiz);
        raiz.setBounds(182, 146, 41, 30);

        borrar.setBackground(new java.awt.Color(225, 251, 255));
        borrar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        borrar.setForeground(new java.awt.Color(255, 255, 255));
        borrar.setText("C");
        borrar.setAlignmentY(0.7F);
        borrar.setContentAreaFilled(false);
        borrar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        getContentPane().add(borrar);
        borrar.setBounds(96, 82, 41, 30);

        back.setBackground(new java.awt.Color(225, 251, 255));
        back.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/back_blnco.png"))); // NOI18N
        back.setToolTipText("");
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(10, 82, 84, 30);

        igual.setBackground(new java.awt.Color(225, 251, 255));
        igual.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        igual.setForeground(new java.awt.Color(255, 255, 255));
        igual.setText("=");
        igual.setContentAreaFilled(false);
        igual.setMargin(new java.awt.Insets(0, 0, 0, 0));
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });
        getContentPane().add(igual);
        igual.setBounds(139, 210, 84, 30);

        negar.setBackground(new java.awt.Color(225, 251, 255));
        negar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        negar.setForeground(new java.awt.Color(255, 255, 255));
        negar.setText("±");
        negar.setAlignmentY(0.7F);
        negar.setContentAreaFilled(false);
        negar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        negar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        negar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negarActionPerformed(evt);
            }
        });
        getContentPane().add(negar);
        negar.setBounds(139, 82, 41, 30);

        unoentre.setBackground(new java.awt.Color(225, 251, 255));
        unoentre.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        unoentre.setForeground(new java.awt.Color(255, 255, 255));
        unoentre.setText("1/x");
        unoentre.setAlignmentY(0.7F);
        unoentre.setContentAreaFilled(false);
        unoentre.setMargin(new java.awt.Insets(0, 0, 0, 0));
        unoentre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoentreActionPerformed(evt);
            }
        });
        getContentPane().add(unoentre);
        unoentre.setBounds(182, 82, 41, 30);

        porcentaje.setBackground(new java.awt.Color(225, 251, 255));
        porcentaje.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        porcentaje.setForeground(new java.awt.Color(255, 255, 255));
        porcentaje.setText("%");
        porcentaje.setAlignmentY(0.7F);
        porcentaje.setContentAreaFilled(false);
        porcentaje.setMargin(new java.awt.Insets(0, 0, 0, 0));
        porcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porcentajeActionPerformed(evt);
            }
        });
        getContentPane().add(porcentaje);
        porcentaje.setBounds(182, 114, 41, 30);

        salida2.setBackground(new java.awt.Color(225, 251, 255));
        salida2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        salida2.setForeground(new java.awt.Color(255, 255, 255));
        salida2.setToolTipText("");
        salida2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        salida2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(salida2);
        salida2.setBounds(10, 11, 213, 24);

        salida.setBackground(new java.awt.Color(225, 251, 255));
        salida.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        salida.setForeground(new java.awt.Color(255, 255, 255));
        salida.setText("0");
        salida.setToolTipText("");
        salida.setAlignmentX(0.5F);
        salida.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        salida.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        salida.setFocusable(false);
        getContentPane().add(salida);
        salida.setBounds(10, 35, 213, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/6681971133_e93ed423ce_z.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 240, 250);

        jMenu1.setText("Edicion");

        jMenuItem1.setText("Copiar");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Pegar");
        jMenu1.add(jMenuItem2);

        Opciones.add(jMenu1);

        jMenu2.setText("Opciones");
        Opciones.add(jMenu2);

        setJMenuBar(Opciones);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        // TODO add your handling code here:
        if (cadena.length()!=16){
            cadena += 5;
            this.salida.setText(cadena);
        } else {
            Toolkit.getDefaultToolkit().beep();            
        }    
    }//GEN-LAST:event_num5ActionPerformed

    private void masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masActionPerformed
        // TODO add your handling code here:
        operacion="+";
        
        if (op == false){
            if(cadena==""){
                cadena="0";
            }
             if(cadena.charAt(cadena.length()-1)==','){
                cadena = cadena.substring(0,cadena.length()-1);
                this.salida.setText(cadena);
            }
            cadena = cadena.replace(",", ".");
            numero = Double.parseDouble(cadena);
            cadena = cadena.replace('.', ',');
            cadena2 += cadena + " + ";
            op=true;
        } else {
            if (cadena2.length()!=0){
                cadena2 = cadena2.substring(0,cadena2.length()-2);
                cadena2+= "+ ";
            } else {
                cadena2=Double.toString(numero);
                cadena2 = cadena2.replace('.', ',');
                if (cadena2.charAt(cadena2.length()-1)=='0' && cadena2.charAt(cadena2.length()-2)==','){
                    cadena2 = cadena2.substring(0,cadena2.length()-1);
                    cadena2 = cadena2.substring(0,cadena2.length()-1);
                }
                cadena2+= " + ";
            }
        }
        this.salida2.setText(cadena2);
        if ("".equals(cadena)){
            cadena="0";
        }
        ans=Double.parseDouble(cadena);
        cadena="";
    }//GEN-LAST:event_masActionPerformed

    private void raizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raizActionPerformed
        // TODO add your handling code here:
       
            if ("".equals(cadena)){
                cadena=Double.toString(ans);
            }
            
            cadena = cadena.replace(",", ".");
            numero= Double.parseDouble(cadena);
            if (cadena.charAt(cadena.length()-1)=='0' && cadena.charAt(cadena.length()-2)=='.'){
                    cadena = cadena.substring(0,cadena.length()-1);
                    cadena = cadena.substring(0,cadena.length()-1);
            }
            
            numero= Math.sqrt(numero);
            cadena2= "√("+cadena+")  ";  
            cadena=Double.toString(numero);
            if (cadena.charAt(cadena.length()-1)=='0' && cadena.charAt(cadena.length()-2)=='.'){
                    cadena = cadena.substring(0,cadena.length()-1);
                    cadena = cadena.substring(0,cadena.length()-1);
            }
            cadena = cadena.replace('.', ',');
            cadena2 = cadena2.replace('.', ',');
            this.salida.setText(cadena);
            this.salida2.setText(cadena2);
            cadena="";
            ans=numero;
            op=true;     
            
             
    }//GEN-LAST:event_raizActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        // TODO add your handling code here:
         cadena ="";
         cadena2="";
         op=false;
         ans=0;
         this.salida.setText("0");
         this.salida2.setText("");
    }//GEN-LAST:event_borrarActionPerformed

    private void negarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_negarActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton29ActionPerformed

    private void unoentreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoentreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unoentreActionPerformed

    private void porcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porcentajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_porcentajeActionPerformed

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9ActionPerformed
        // TODO add your handling code here:
        if (cadena.length()!=16){
            cadena += 9;
            this.salida.setText(cadena);
        } else {
            Toolkit.getDefaultToolkit().beep();            
        }    
    }//GEN-LAST:event_num9ActionPerformed

    private void num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num0ActionPerformed
        if (cadena.length()!=0){       
            if (cadena.length()!=16){
                cadena += 0;
                this.salida.setText(cadena);
            } else {
                 Toolkit.getDefaultToolkit().beep();            
            }    
        }
    }//GEN-LAST:event_num0ActionPerformed

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        // TODO add your handling code here:
        if (cadena.length()!=16){
            cadena += 1;
            this.salida.setText(cadena);
        } else {
            Toolkit.getDefaultToolkit().beep();            
        }    
    }//GEN-LAST:event_num1ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        // TODO add your handling code here:
        if (cadena.length()!=16){
            cadena += 2;
            this.salida.setText(cadena);
        } else {
            Toolkit.getDefaultToolkit().beep();            
        }    
    }//GEN-LAST:event_num2ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
        // TODO add your handling code here:
         if (cadena.length()!=16){
            cadena += 3;
            this.salida.setText(cadena);
        } else {
            Toolkit.getDefaultToolkit().beep();            
        }    
    }//GEN-LAST:event_num3ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        // TODO add your handling code here 
        if (cadena.length()!=16){
            cadena += 4;
            this.salida.setText(cadena);
        } else {
            Toolkit.getDefaultToolkit().beep();            
        }    
    }//GEN-LAST:event_num4ActionPerformed

    private void num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num6ActionPerformed
        // TODO add your handling code here:
        if (cadena.length()!=16){
            cadena += 6;
            this.salida.setText(cadena);
        } else {
            Toolkit.getDefaultToolkit().beep();            
        }    
    }//GEN-LAST:event_num6ActionPerformed

    private void num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num7ActionPerformed
        // TODO add your handling code here:
        if (cadena.length()!=16){
            cadena += 7;
            this.salida.setText(cadena);
        } else {
            Toolkit.getDefaultToolkit().beep();            
        }    
    }//GEN-LAST:event_num7ActionPerformed

    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8ActionPerformed
        // TODO add your handling code here:
        if (cadena.length()!=16){
            cadena += 8;
            this.salida.setText(cadena);
        } else {
            Toolkit.getDefaultToolkit().beep();            
        }    
    }//GEN-LAST:event_num8ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        if ((cadena.length()== 1) || (cadena.length()== 0)){
            
            if (cadena.length()== 0){
                 Toolkit.getDefaultToolkit().beep(); 
            }
            
            if (!"".equals(cadena)){
                cadena ="";
            }
            
            this.salida.setText("0");
        } else {
            cadena = cadena.substring(0,cadena.length()-1);            
            this.salida.setText(cadena);
        }
    }//GEN-LAST:event_backActionPerformed

    private void menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosActionPerformed
        // TODO add your handling code here:
        operacion="-";
        
        if (op == false){
            if("".equals(cadena)){
                cadena="0";
            }
             if(cadena.charAt(cadena.length()-1)==','){
                cadena = cadena.substring(0,cadena.length()-1);
                this.salida.setText(cadena);
            }
            cadena = cadena.replace(",", ".");
            numero = Double.parseDouble(cadena);
            cadena = cadena.replace('.', ',');
            cadena2 += cadena + " - ";
            op=true;
        } else {
            if (cadena2.length()!=0){
                cadena2 = cadena2.substring(0,cadena2.length()-2);
                cadena2+= "- ";
            } else {
                cadena2=Double.toString(numero);
                cadena2 = cadena2.replace('.', ',');
                if (cadena2.charAt(cadena2.length()-1)=='0' && cadena2.charAt(cadena2.length()-2)==','){
                    cadena2 = cadena2.substring(0,cadena2.length()-1);
                    cadena2 = cadena2.substring(0,cadena2.length()-1);
                }
                cadena2+= " - ";
            }
        }
        this.salida2.setText(cadena2);
        cadena="";
    }//GEN-LAST:event_menosActionPerformed

    private void porActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porActionPerformed
        // TODO add your handling code here:
         operacion="*";
        
        if (op == false){
            if("".equals(cadena)){
                cadena="0";
            }
             if(cadena.charAt(cadena.length()-1)==','){
                cadena = cadena.substring(0,cadena.length()-1);
                this.salida.setText(cadena);
            }
            cadena = cadena.replace(",", ".");
            numero = Double.parseDouble(cadena);
            cadena = cadena.replace('.', ',');
            cadena2 += cadena + " * ";
            op=true;
        } else {
            if (cadena2.length()!=0){
                cadena2 = cadena2.substring(0,cadena2.length()-2);
                cadena2+= "* ";
            } else {
                cadena2=Double.toString(numero);
                cadena2 = cadena2.replace('.', ',');
                if (cadena2.charAt(cadena2.length()-1)=='0' && cadena2.charAt(cadena2.length()-2)==','){
                    cadena2 = cadena2.substring(0,cadena2.length()-1);
                    cadena2 = cadena2.substring(0,cadena2.length()-1);
                }
                cadena2+= " * ";
            }
        }
        this.salida2.setText(cadena2);
        cadena="";
    }//GEN-LAST:event_porActionPerformed

    private void entreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entreActionPerformed
        // TODO add your handling code here:
         operacion="/";
        
        if (op == false){
            if("".equals(cadena)){
                cadena="0";
            }
             if(cadena.charAt(cadena.length()-1)==','){
                cadena = cadena.substring(0,cadena.length()-1);
                this.salida.setText(cadena);
            }
            cadena = cadena.replace(",", ".");
            numero = Double.parseDouble(cadena);
            cadena = cadena.replace('.', ',');
            cadena2 += cadena + " / ";
            op=true;
        } else {
            if (cadena2.length()!=0){
                cadena2 = cadena2.substring(0,cadena2.length()-2);
                cadena2+= "/ ";
            } else {
                cadena2=Double.toString(numero);
                cadena2 = cadena2.replace('.', ',');
                if (cadena2.charAt(cadena2.length()-1)=='0' && cadena2.charAt(cadena2.length()-2)==','){
                    cadena2 = cadena2.substring(0,cadena2.length()-1);
                    cadena2 = cadena2.substring(0,cadena2.length()-1);
                }
                cadena2+= " / ";
            }
        }
        this.salida2.setText(cadena2);
        cadena="";
    }//GEN-LAST:event_entreActionPerformed

    private void comaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comaActionPerformed
        // TODO add your handling code here:
        if (cadena.length()!=15){
            if (cadena.indexOf(",")!=-1){
                Toolkit.getDefaultToolkit().beep();   
            } else {
                if ("".equals(cadena)){
                   cadena="0";                   
                }
                cadena += ",";              
            }
            this.salida.setText(cadena);
        } else {
            Toolkit.getDefaultToolkit().beep();            
        } 
    }//GEN-LAST:event_comaActionPerformed

    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
        
                
        if ("+".equals(operacion)){
            
            cadena = cadena.replace(",", ".");
            numero2 = Double.parseDouble(cadena);
            cadena = cadena.replace('.', ',');
            cadena2 += cadena;
            this.salida2.setText(cadena2);
            cadena2 ="";
            numero = numero + numero2;
            cadena =  Double.toString(numero);
            cadena = cadena.replace('.', ',');
            if (cadena.charAt(cadena.length()-1)=='0' && cadena.charAt(cadena.length()-2)==','){
                cadena = cadena.substring(0,cadena.length()-1);
                cadena = cadena.substring(0,cadena.length()-1);
            }
            this.salida.setText(cadena);
            
        }
         if ("-".equals(operacion)){
            
            cadena = cadena.replace(",", ".");
            numero2 = Double.parseDouble(cadena);
            cadena = cadena.replace('.', ',');
            cadena2 += cadena;
            this.salida2.setText(cadena2);
            cadena2 ="";
            numero = numero - numero2;
            cadena =  Double.toString(numero);
            cadena = cadena.replace('.', ',');
            if (cadena.charAt(cadena.length()-1)=='0' && cadena.charAt(cadena.length()-2)==','){
                cadena = cadena.substring(0,cadena.length()-1);
                cadena = cadena.substring(0,cadena.length()-1);
            }
            this.salida.setText(cadena);
            
        }
         
        if ("*".equals(operacion)){
            
            cadena = cadena.replace(",", ".");
            numero2 = Double.parseDouble(cadena);
            cadena = cadena.replace('.', ',');
            cadena2 += cadena;
            this.salida2.setText(cadena2);
            cadena2 ="";
            numero = numero * numero2;
            cadena =  Double.toString(numero);
            cadena = cadena.replace('.', ',');
            if (cadena.charAt(cadena.length()-1)=='0' && cadena.charAt(cadena.length()-2)==','){
                cadena = cadena.substring(0,cadena.length()-1);
                cadena = cadena.substring(0,cadena.length()-1);
            }
            this.salida.setText(cadena);
            
        }
        
        if ("/".equals(operacion)){
            
            cadena = cadena.replace(",", ".");
            numero2 = Double.parseDouble(cadena);
            cadena = cadena.replace('.', ',');
            cadena2 += cadena;
            this.salida2.setText(cadena2);
            cadena2 ="";
            numero = numero / numero2;
            cadena =  Double.toString(numero);
            cadena = cadena.replace('.', ',');
            if (cadena.charAt(cadena.length()-1)=='0' && cadena.charAt(cadena.length()-2)==','){
                cadena = cadena.substring(0,cadena.length()-1);
                cadena = cadena.substring(0,cadena.length()-1);
            }
            this.salida.setText(cadena);
            
        }
        ans=numero;
        cadena="";
        operacion="";
        
    }//GEN-LAST:event_igualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Opciones;
    private javax.swing.JButton back;
    private javax.swing.JButton borrar;
    private javax.swing.JButton coma;
    private javax.swing.JButton entre;
    private javax.swing.JButton igual;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.border.LineBorder lineBorder1;
    private javax.swing.JButton mas;
    private javax.swing.JButton menos;
    private javax.swing.JButton negar;
    private javax.swing.JButton num0;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JButton por;
    private javax.swing.JButton porcentaje;
    private javax.swing.JButton raiz;
    public javax.swing.JLabel salida;
    public javax.swing.JLabel salida2;
    private javax.swing.JButton unoentre;
    // End of variables declaration//GEN-END:variables
}
